--[=[
 d888b  db    db d888888b      .d888b.      db      db    db  .d8b.  
88' Y8b 88    88   `88'        VP  `8D      88      88    88 d8' `8b 
88      88    88    88            odD'      88      88    88 88ooo88 
88  ooo 88    88    88          .88'        88      88    88 88~~~88 
88. ~8~ 88b  d88   .88.        j88.         88booo. 88b  d88 88   88    @uniquadev
 Y888P  ~Y8888P' Y888888P      888888D      Y88888P ~Y8888P' YP   YP  CONVERTER 

designed using localmaze gui creator
]=]

-- Instances: 35 | Scripts: 0 | Modules: 0 | Tags: 0
local LMG2L = {};

-- Players.Haker_1234567V3.PlayerGui.ScreenGui
LMG2L["ScreenGui_1"] = Instance.new("ScreenGui", game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui"));
LMG2L["ScreenGui_1"]["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling;


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute
LMG2L["execute_2"] = Instance.new("Frame", LMG2L["ScreenGui_1"]);
LMG2L["execute_2"]["BorderSizePixel"] = 2;
LMG2L["execute_2"]["BackgroundColor3"] = Color3.fromRGB(200, 200, 200);
LMG2L["execute_2"]["Size"] = UDim2.new(0, 726, 0, 414);
LMG2L["execute_2"]["Position"] = UDim2.new(0, 218, 0, 84);
LMG2L["execute_2"]["Name"] = [[execute]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextButton9
LMG2L["TextButton9_3"] = Instance.new("TextButton", LMG2L["execute_2"]);
LMG2L["TextButton9_3"]["TextWrapped"] = true;
LMG2L["TextButton9_3"]["BorderSizePixel"] = 2;
LMG2L["TextButton9_3"]["AutoLocalize"] = false;
LMG2L["TextButton9_3"]["TextScaled"] = true;
LMG2L["TextButton9_3"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton9_3"]["BorderMode"] = Enum.BorderMode.Inset;
LMG2L["TextButton9_3"]["Size"] = UDim2.new(0, 52, 0, 32);
LMG2L["TextButton9_3"]["Text"] = [[idk]];
LMG2L["TextButton9_3"]["Name"] = [[TextButton9]];
LMG2L["TextButton9_3"]["Position"] = UDim2.new(0, 560, 0, 34);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextButton7
LMG2L["TextButton7_4"] = Instance.new("TextButton", LMG2L["execute_2"]);
LMG2L["TextButton7_4"]["TextWrapped"] = true;
LMG2L["TextButton7_4"]["BorderSizePixel"] = 2;
LMG2L["TextButton7_4"]["AutoLocalize"] = false;
LMG2L["TextButton7_4"]["TextScaled"] = true;
LMG2L["TextButton7_4"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton7_4"]["BorderMode"] = Enum.BorderMode.Inset;
LMG2L["TextButton7_4"]["Size"] = UDim2.new(0, 54, 0, 32);
LMG2L["TextButton7_4"]["Text"] = [[dex]];
LMG2L["TextButton7_4"]["Name"] = [[TextButton7]];
LMG2L["TextButton7_4"]["Position"] = UDim2.new(0, 668, 0, 34);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextButton2
LMG2L["TextButton2_5"] = Instance.new("TextButton", LMG2L["execute_2"]);
LMG2L["TextButton2_5"]["TextWrapped"] = true;
LMG2L["TextButton2_5"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_5"]["AutoLocalize"] = false;
LMG2L["TextButton2_5"]["TextScaled"] = true;
LMG2L["TextButton2_5"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_5"]["BorderMode"] = Enum.BorderMode.Inset;
LMG2L["TextButton2_5"]["Size"] = UDim2.new(0, 102, 0, 32);
LMG2L["TextButton2_5"]["Text"] = [[Admin panel]];
LMG2L["TextButton2_5"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_5"]["Position"] = UDim2.new(0, 110, 0, 34);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextButton8
LMG2L["TextButton8_6"] = Instance.new("TextButton", LMG2L["execute_2"]);
LMG2L["TextButton8_6"]["TextWrapped"] = true;
LMG2L["TextButton8_6"]["BorderSizePixel"] = 2;
LMG2L["TextButton8_6"]["AutoLocalize"] = false;
LMG2L["TextButton8_6"]["TextScaled"] = true;
LMG2L["TextButton8_6"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton8_6"]["BorderMode"] = Enum.BorderMode.Inset;
LMG2L["TextButton8_6"]["Size"] = UDim2.new(0, 54, 0, 32);
LMG2L["TextButton8_6"]["Text"] = [[R6]];
LMG2L["TextButton8_6"]["Name"] = [[TextButton8]];
LMG2L["TextButton8_6"]["Position"] = UDim2.new(0, 612, 0, 34);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextButton
LMG2L["TextButton_7"] = Instance.new("TextButton", LMG2L["execute_2"]);
LMG2L["TextButton_7"]["TextWrapped"] = true;
LMG2L["TextButton_7"]["BorderSizePixel"] = 2;
LMG2L["TextButton_7"]["AutoLocalize"] = false;
LMG2L["TextButton_7"]["TextScaled"] = true;
LMG2L["TextButton_7"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_7"]["BorderMode"] = Enum.BorderMode.Inset;
LMG2L["TextButton_7"]["Size"] = UDim2.new(0, 102, 0, 32);
LMG2L["TextButton_7"]["Text"] = [[executor]];
LMG2L["TextButton_7"]["Position"] = UDim2.new(0, 4, 0, 34);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextButton4
LMG2L["TextButton4_8"] = Instance.new("TextButton", LMG2L["execute_2"]);
LMG2L["TextButton4_8"]["TextWrapped"] = true;
LMG2L["TextButton4_8"]["BorderSizePixel"] = 2;
LMG2L["TextButton4_8"]["AutoLocalize"] = false;
LMG2L["TextButton4_8"]["TextScaled"] = true;
LMG2L["TextButton4_8"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton4_8"]["Size"] = UDim2.new(0, 146, 0, 58);
LMG2L["TextButton4_8"]["Text"] = [[Clear]];
LMG2L["TextButton4_8"]["Name"] = [[TextButton4]];
LMG2L["TextButton4_8"]["Position"] = UDim2.new(0, 154, 0, 350);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextButton3
LMG2L["TextButton3_9"] = Instance.new("TextButton", LMG2L["execute_2"]);
LMG2L["TextButton3_9"]["TextWrapped"] = true;
LMG2L["TextButton3_9"]["BorderSizePixel"] = 2;
LMG2L["TextButton3_9"]["AutoLocalize"] = false;
LMG2L["TextButton3_9"]["TextScaled"] = true;
LMG2L["TextButton3_9"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton3_9"]["Size"] = UDim2.new(0, 146, 0, 58);
LMG2L["TextButton3_9"]["Text"] = [[execute]];
LMG2L["TextButton3_9"]["Name"] = [[TextButton3]];
LMG2L["TextButton3_9"]["Position"] = UDim2.new(0, 4, 0, 350);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextButton5
LMG2L["TextButton5_a"] = Instance.new("TextButton", LMG2L["execute_2"]);
LMG2L["TextButton5_a"]["TextWrapped"] = true;
LMG2L["TextButton5_a"]["BorderSizePixel"] = 2;
LMG2L["TextButton5_a"]["TextScaled"] = true;
LMG2L["TextButton5_a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton5_a"]["Size"] = UDim2.new(0, 146, 0, 58);
LMG2L["TextButton5_a"]["Text"] = [[Copy]];
LMG2L["TextButton5_a"]["Name"] = [[TextButton5]];
LMG2L["TextButton5_a"]["Position"] = UDim2.new(0, 304, 0, 350);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ImageLabel
LMG2L["ImageLabel_b"] = Instance.new("ImageLabel", LMG2L["execute_2"]);
LMG2L["ImageLabel_b"]["BorderSizePixel"] = 0;
LMG2L["ImageLabel_b"]["BackgroundColor3"] = Color3.fromRGB(155, 155, 155);
-- LMG2L["ImageLabel_b"]["ImageContent"] = ;
LMG2L["ImageLabel_b"]["Image"] = [[rbxassetid://73185495890754]];
LMG2L["ImageLabel_b"]["Size"] = UDim2.new(0, 36, 0, 30);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextBox
LMG2L["TextBox_c"] = Instance.new("TextBox", LMG2L["execute_2"]);
LMG2L["TextBox_c"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextBox_c"]["BorderSizePixel"] = 2;
LMG2L["TextBox_c"]["TextSize"] = 12;
LMG2L["TextBox_c"]["TextYAlignment"] = Enum.TextYAlignment.Top;
LMG2L["TextBox_c"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextBox_c"]["PlaceholderText"] = [[script is by kvsna3545 ok?]];
LMG2L["TextBox_c"]["Size"] = UDim2.new(0, 550, 0, 272);
LMG2L["TextBox_c"]["Position"] = UDim2.new(0, 6, 0, 72);
LMG2L["TextBox_c"]["Text"] = [[]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.TextLabel
LMG2L["TextLabel_d"] = Instance.new("TextLabel", LMG2L["execute_2"]);
LMG2L["TextLabel_d"]["TextWrapped"] = true;
LMG2L["TextLabel_d"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_d"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel_d"]["TextYAlignment"] = Enum.TextYAlignment.Top;
LMG2L["TextLabel_d"]["TextScaled"] = true;
LMG2L["TextLabel_d"]["BackgroundColor3"] = Color3.fromRGB(158, 158, 158);
LMG2L["TextLabel_d"]["Size"] = UDim2.new(0, 690, 0, 30);
LMG2L["TextLabel_d"]["Text"] = [[Ss bypass executor by kvsna3545]];
LMG2L["TextLabel_d"]["Position"] = UDim2.new(0, 36, 0, 0);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame
LMG2L["ScrollingFrame_e"] = Instance.new("ScrollingFrame", LMG2L["execute_2"]);
LMG2L["ScrollingFrame_e"]["BorderSizePixel"] = 0;
LMG2L["ScrollingFrame_e"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["ScrollingFrame_e"]["Size"] = UDim2.new(0, 158, 0, 338);
LMG2L["ScrollingFrame_e"]["Position"] = UDim2.new(0, 564, 0, 70);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton9
LMG2L["TextButton9_f"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton9_f"]["BorderSizePixel"] = 0;
LMG2L["TextButton9_f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton9_f"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton9_f"]["Text"] = [[Thank you project]];
LMG2L["TextButton9_f"]["Name"] = [[TextButton9]];
LMG2L["TextButton9_f"].MouseButton1Click:Connect(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/kvsna3545-pixel/Thank-you-project/refs/heads/main/Main.lua"))()
end)


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton7
LMG2L["TextButton7_10"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton7_10"]["BorderSizePixel"] = 0;
LMG2L["TextButton7_10"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton7_10"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton7_10"]["Name"] = [[TextButton7]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton2
LMG2L["TextButton2_11"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton2_11"]["BorderSizePixel"] = 0;
LMG2L["TextButton2_11"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_11"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton2_11"]["Name"] = [[TextButton2]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton8
LMG2L["TextButton8_12"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton8_12"]["BorderSizePixel"] = 0;
LMG2L["TextButton8_12"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton8_12"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton8_12"]["Name"] = [[TextButton8]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton12
LMG2L["TextButton12_13"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton12_13"]["BorderSizePixel"] = 0;
LMG2L["TextButton12_13"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton12_13"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton12_13"]["Name"] = [[TextButton12]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton
LMG2L["TextButton_14"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton_14"]["BorderSizePixel"] = 0;
LMG2L["TextButton_14"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_14"]["Size"] = UDim2.new(0, 158, 0, 32);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton4
LMG2L["TextButton4_15"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton4_15"]["BorderSizePixel"] = 0;
LMG2L["TextButton4_15"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton4_15"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton4_15"]["Name"] = [[TextButton4]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton11
LMG2L["TextButton11_16"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton11_16"]["BorderSizePixel"] = 0;
LMG2L["TextButton11_16"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton11_16"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton11_16"]["Name"] = [[TextButton11]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton10
LMG2L["TextButton10_17"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton10_17"]["BorderSizePixel"] = 0;
LMG2L["TextButton10_17"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton10_17"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton10_17"]["Name"] = [[TextButton10]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton6
LMG2L["TextButton6_18"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton6_18"]["BorderSizePixel"] = 0;
LMG2L["TextButton6_18"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton6_18"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton6_18"]["Name"] = [[TextButton6]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton5
LMG2L["TextButton5_19"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton5_19"]["BorderSizePixel"] = 0;
LMG2L["TextButton5_19"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton5_19"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton5_19"]["Name"] = [[TextButton5]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.UIListLayout
LMG2L["UIListLayout_1a"] = Instance.new("UIListLayout", LMG2L["ScrollingFrame_e"]);



-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.ScrollingFrame.TextButton3
LMG2L["TextButton3_1b"] = Instance.new("TextButton", LMG2L["ScrollingFrame_e"]);
LMG2L["TextButton3_1b"]["BorderSizePixel"] = 0;
LMG2L["TextButton3_1b"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton3_1b"]["Size"] = UDim2.new(0, 158, 0, 32);
LMG2L["TextButton3_1b"]["Name"] = [[TextButton3]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.execute.UIDragDetector
LMG2L["UIDragDetector_1c"] = Instance.new("UIDragDetector", LMG2L["execute_2"]);



-- Players.Haker_1234567V3.PlayerGui.ScreenGui.admin panel
LMG2L["admin panel_1d"] = Instance.new("Frame", LMG2L["ScreenGui_1"]);
LMG2L["admin panel_1d"]["BorderSizePixel"] = 2;
LMG2L["admin panel_1d"]["BackgroundColor3"] = Color3.fromRGB(200, 200, 200);
LMG2L["admin panel_1d"]["Size"] = UDim2.new(0, 726, 0, 414);
LMG2L["admin panel_1d"]["Position"] = UDim2.new(0, 220, 0, 86);
LMG2L["admin panel_1d"]["Name"] = [[admin panel]];


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.admin panel.TextButton2
LMG2L["TextButton2_1e"] = Instance.new("TextButton", LMG2L["admin panel_1d"]);
LMG2L["TextButton2_1e"]["TextWrapped"] = true;
LMG2L["TextButton2_1e"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_1e"]["AutoLocalize"] = false;
LMG2L["TextButton2_1e"]["TextScaled"] = true;
LMG2L["TextButton2_1e"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_1e"]["BorderMode"] = Enum.BorderMode.Inset;
LMG2L["TextButton2_1e"]["Size"] = UDim2.new(0, 102, 0, 32);
LMG2L["TextButton2_1e"]["Text"] = [[Admin panel]];
LMG2L["TextButton2_1e"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_1e"]["Position"] = UDim2.new(0, 110, 0, 34);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.admin panel.ImageLabel
LMG2L["ImageLabel_1f"] = Instance.new("ImageLabel", LMG2L["admin panel_1d"]);
LMG2L["ImageLabel_1f"]["BorderSizePixel"] = 0;
LMG2L["ImageLabel_1f"]["BackgroundColor3"] = Color3.fromRGB(155, 155, 155);
-- LMG2L["ImageLabel_1f"]["ImageContent"] = ;
LMG2L["ImageLabel_1f"]["Image"] = [[rbxassetid://73185495890754]];
LMG2L["ImageLabel_1f"]["Size"] = UDim2.new(0, 36, 0, 30);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.admin panel.TextLabel
LMG2L["TextLabel_20"] = Instance.new("TextLabel", LMG2L["admin panel_1d"]);
LMG2L["TextLabel_20"]["TextWrapped"] = true;
LMG2L["TextLabel_20"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_20"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel_20"]["TextYAlignment"] = Enum.TextYAlignment.Top;
LMG2L["TextLabel_20"]["TextScaled"] = true;
LMG2L["TextLabel_20"]["BackgroundColor3"] = Color3.fromRGB(158, 158, 158);
LMG2L["TextLabel_20"]["Size"] = UDim2.new(0, 690, 0, 30);
LMG2L["TextLabel_20"]["Text"] = [[Ss bypass executor by kvsna3545]];
LMG2L["TextLabel_20"]["Position"] = UDim2.new(0, 36, 0, 0);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.admin panel.TextButton
LMG2L["TextButton_21"] = Instance.new("TextButton", LMG2L["admin panel_1d"]);
LMG2L["TextButton_21"]["TextWrapped"] = true;
LMG2L["TextButton_21"]["BorderSizePixel"] = 2;
LMG2L["TextButton_21"]["AutoLocalize"] = false;
LMG2L["TextButton_21"]["TextScaled"] = true;
LMG2L["TextButton_21"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_21"]["BorderMode"] = Enum.BorderMode.Inset;
LMG2L["TextButton_21"]["Size"] = UDim2.new(0, 102, 0, 32);
LMG2L["TextButton_21"]["Text"] = [[executor]];
LMG2L["TextButton_21"]["Position"] = UDim2.new(0, 4, 0, 34);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.admin panel.TextLabel
LMG2L["TextLabel_22"] = Instance.new("TextLabel", LMG2L["admin panel_1d"]);
LMG2L["TextLabel_22"]["TextWrapped"] = true;
LMG2L["TextLabel_22"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_22"]["TextSize"] = 100;
LMG2L["TextLabel_22"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_22"]["Size"] = UDim2.new(0, 722, 0, 334);
LMG2L["TextLabel_22"]["Text"] = [[ยังทำไม่เสร็จ]];
LMG2L["TextLabel_22"]["Position"] = UDim2.new(0, 2, 0, 74);


-- Players.Haker_1234567V3.PlayerGui.ScreenGui.admin panel.UIDragDetector
LMG2L["UIDragDetector_23"] = Instance.new("UIDragDetector", LMG2L["admin panel_1d"]);

-- SERVICES
local Players = game:GetService("Players")
local player = Players.LocalPlayer

-- VARIABLES
local textBox = LMG2L["TextBox_c"]
local executeBtn = LMG2L["TextButton3_9"]
local clearBtn = LMG2L["TextButton4_8"]
local copyBtn = LMG2L["TextButton5_a"]

-- EXECUTE (รันโค้ด)
executeBtn.MouseButton1Click:Connect(function()
	local code = textBox.Text
	
	if code ~= "" then
		local success, err = pcall(function()
			code
		end)
		
		if not success then
			warn("Error: "..err)
		end
	end
end)

-- CLEAR (ล้างช่อง)
clearBtn.MouseButton1Click:Connect(function()
	textBox.Text = ""
end)

-- COPY (คัดลอก)
copyBtn.MouseButton1Click:Connect(function()
	if setclipboard then
		setclipboard(textBox.Text)
	end
end)

-- TAB SYSTEM

local executorFrame = LMG2L["execute_2"]
local adminFrame = LMG2L["admin panel_1d"]

-- ปุ่มในหน้า executor
local openAdminBtn = LMG2L["TextButton2_5"] -- Admin panel

-- ปุ่มในหน้า admin panel
local openExecutorBtn = LMG2L["TextButton_21"] -- executor

-- เริ่มต้นให้แสดง executor อย่างเดียว
executorFrame.Visible = true
adminFrame.Visible = false

-- ไปหน้า ADMIN
openAdminBtn.MouseButton1Click:Connect(function()
	executorFrame.Visible = false
	adminFrame.Visible = true
end)

-- กลับหน้า EXECUTOR
openExecutorBtn.MouseButton1Click:Connect(function()
	adminFrame.Visible = false
	executorFrame.Visible = true
end)



return LMG2L["ScreenGui_1"], require;
